### ISSUE TITLE
не собирается под ядро 6.5 (на Ubuntu 22.04)

### ISSUE THREAD

**Issue by igroc2** [ifritee/mxu11x0#1]
Не получается собраться под ядро 6.5. Стоит Ubuntu 22.04.  В файле `build.log`:
```
  ERROR: Kernel configuration is invalid.
         include/generated/autoconf.h or include/config/auto.conf are missing.
         Run 'make oldconfig && make prepare' on kernel src to fix it.

make[2]: *** [/usr/src/linux-headers-6.5.0-17-generic/Makefile:817: include/config/auto.conf] Error 1
make[1]: *** [Makefile:234: __sub-make] Error 2
```

Может есть идеи что можно подкорректировать, чтобы собралось? Заранее благодарю

**Comment by ifritee** [comment]
Добрый день, внес правки - посмотрите.

пн, 19 февр. 2024 г., 12:05 Rusakov Anton ***@***.***>:

**Comment by igroc2** [comment]
Отлично, Спасибо Большое, всё собралось, только gcc-12 еще доустановить пришлось
